package com.avaglir.knave.map

import com.avaglir.knave.util._
import simplex.SimplexNoise

object GenMap extends Persist {
  var large = SimplexNoise()
  var small = SimplexNoise()

  private val smallScale = 0.262
  private val largeScale = 0.06
  private val smallWeight = 0.31
  private val largeWeight = 0.56

  private val ctrMag = math.sqrt(2)/2

  private val smallFalloff = 0.91
  private val largeFalloff = 0.18
  private val smallRadius = smallFalloff * ctrMag
  private val largeRadius = largeFalloff * ctrMag

  private val threshhold = 0.35
  private val mapScale = 30000

  def apply(x: Vector2): Float = apply(x.x, x.y)
  def apply(x: Int, y: Int): Float = apply(x.toFloat/mapScale, y.toFloat/mapScale)
  def apply(x: Float, y: Float): Float = {
    val dx = x - 0.5
    val dy = y - 0.5
    val ctrDist = math.sqrt(dx * dx + dy * dy)

    val sm = if (ctrDist > smallRadius) 1 - (ctrDist - smallRadius) / (ctrMag - smallRadius) else 1
    val lg = if (ctrDist > largeRadius) 1 - (ctrDist - largeRadius) / (ctrMag - largeRadius) else 1

    val lgVal = large.eval(x / largeScale, y / largeScale) * largeWeight * (lg * lg)
    val smVal = small.eval(x / smallScale, y / smallScale) * smallWeight * (sm * sm)

    (lgVal + smVal).toFloat.clamp
  }

  /**
    * Builds a square map of the specified side length.
    * @param res The side length of the map.
    * @return A square 2d array of the specified dimensions, filled with the map
    *         generated by GenMap.
    */
  def emitMap(res: Int): Array[Array[Float]] = {
    val out = Array.ofDim[Float](res, res)

    for (i <- 0 until res; j <- 0 until res) {
      out(i)(j) = apply(i.toFloat / res, j.toFloat / res)
    }
    out
  }

  import com.avaglir.knave.util.storage.Pickling._
  import prickle._
  override def persist(): Map[Symbol, String] = Map(
    'simplex_large -> Pickle.intoString(large),
    'simplex_small -> Pickle.intoString(small)
  )

  override def restore(v: Map[Symbol, String]): Unit = {
    large = Unpickle[SimplexNoise].fromString(v('simplex_large)).get
    small = Unpickle[SimplexNoise].fromString(v('simplex_small)).get
  }
  override def key: Symbol = 'mapgen
}
