[package]
name = "knave"
version = "0.1.0"
authors = ["Nathan Perry <avaglir@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.5"
termion = "1.5"
lazy_static = "1.3"
nalgebra = "0.18"
specs = "0.14"
log = "0.4"
fern = "0.5"
chrono = "0.4"
crossbeam-channel = "0.3"
